[project]
name = "rag2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AshutoshSingh058", email = "singhash058@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "langchain>=1.3.17",
    "langchain-anthropic>=1.6.1",
    "langchain-core>=1.6.0",
    "langchain-google-genai>=4.3.5",
    "langchain-openai>=1.6.0",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
]

[project.scripts]
rag2 = "rag2:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
